export const COUNTRY_LIST = 'COUNTRY_LIST';
export const LOADING_TRUE = 'LOADING_TRUE';
export const COUNTRY_SELECTED = 'COUNTRY_SELECTED'; 
export const COUNTRY_FILTER = 'COUNTRY_FILTER'
export const VISA_FILTER = 'VISA_FILTER'
export const TOGGLE_SEARCH_BAR = 'TOGGLE_SEARCH_BAR'
export const VISA_SELECTED = 'VISA_SELECTED'
export const GO_BACK = 'GO_BACK'